language: android
jdk: oraclejdk8
sudo: false

env:
  global:
   - ANDROID_API_LEVEL=27
   - EMULATOR_API_LEVEL=19
   - ANDROID_BUILD_TOOLS_VERSION=27.0.3
   - ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$EMULATOR_API_LEVEL
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
    - add-on
    - extra

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
  - yes | sdkmanager "platforms;android-27"

before_script:
  - cd MyNews
  - chmod +x gradlew
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  - ./gradlew connectedCheck --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)